import type { SessionUser } from "@/lib/auth";

type Role = SessionUser["role"];
type TaskStatus = "TODO" | "IN_PROGRESS" | "REVIEW" | "COMPLETED";
type Priority = "LOW" | "MEDIUM" | "HIGH" | "URGENT";

const baseDate = new Date("2026-05-14T09:00:00.000Z");
const now = baseDate.toISOString();
const addDays = (days: number) =>
  new Date(baseDate.getTime() + days * 24 * 60 * 60 * 1000).toISOString();

export const sampleUser: SessionUser & { imageUrl: string | null } = {
  id: "sample-user-1",
  name: "Priya Sharma",
  email: "demo@taskflow.local",
  role: "ADMIN",
  imageUrl: null,
};

export const sampleTeamMembers = [
  {
    ...sampleUser,
    position: "Engineering Manager",
    department: "Product Engineering",
    availability: "Available",
  },
  {
    id: "sample-user-2",
    name: "Arjun Mehta",
    email: "arjun@taskflow.local",
    role: "MANAGER" as Role,
    imageUrl: null,
    position: "Frontend Lead",
    department: "Web Experience",
    availability: "In sprint",
  },
  {
    id: "sample-user-3",
    name: "Neha Kapoor",
    email: "neha@taskflow.local",
    role: "MEMBER" as Role,
    imageUrl: null,
    position: "Backend Engineer",
    department: "Platform",
    availability: "Focused",
  },
  {
    id: "sample-user-4",
    name: "Rohan Verma",
    email: "rohan@taskflow.local",
    role: "MEMBER" as Role,
    imageUrl: null,
    position: "Product Designer",
    department: "Design",
    availability: "Available",
  },
  {
    id: "sample-user-5",
    name: "Sara Khan",
    email: "sara@taskflow.local",
    role: "MEMBER" as Role,
    imageUrl: null,
    position: "QA Analyst",
    department: "Quality",
    availability: "Reviewing",
  },
];

const memberForProject = (projectId: string, userIds: string[]) =>
  userIds.map((userId) => {
    const user = sampleTeamMembers.find((member) => member.id === userId) ?? sampleTeamMembers[0];
    return {
      id: `member-${projectId}-${user.id}`,
      userId: user.id,
      projectId,
      role: user.role,
      position: user.position,
      createdAt: now,
      user,
    };
  });

export const sampleProjects = [
  {
    id: "project-1",
    title: "Internal Task Manager Rollout",
    description: "Deploy the manager workspace for tracking company projects, team assignments, and deadlines.",
    assignedAt: addDays(-6),
    deadline: addDays(2),
    completedAt: null,
    state: "ONGOING",
    health: "On Track",
    progress: 67,
    ownerId: sampleUser.id,
    deletedAt: null,
    createdAt: now,
    updatedAt: now,
    owner: sampleUser,
    members: memberForProject("project-1", ["sample-user-1", "sample-user-2", "sample-user-3"]),
    _count: { tasks: 3 },
  },
  {
    id: "project-2",
    title: "Client Portal Polish",
    description: "Improve the pages clients use to review work, deadlines, and delivery updates.",
    assignedAt: addDays(-3),
    deadline: addDays(7),
    completedAt: null,
    state: "ONGOING",
    health: "At Risk",
    progress: 42,
    ownerId: sampleUser.id,
    deletedAt: null,
    createdAt: now,
    updatedAt: addDays(1),
    owner: sampleUser,
    members: memberForProject("project-2", ["sample-user-2", "sample-user-4", "sample-user-5"]),
    _count: { tasks: 3 },
  },
  {
    id: "project-3",
    title: "Team Operations Setup",
    description: "Prepare team roles, weekly reporting, and operating rhythm.",
    assignedAt: addDays(-12),
    deadline: addDays(14),
    completedAt: addDays(-1),
    state: "COMPLETED",
    health: "Completed",
    progress: 100,
    ownerId: sampleUser.id,
    deletedAt: null,
    createdAt: now,
    updatedAt: addDays(2),
    owner: sampleUser,
    members: memberForProject("project-3", ["sample-user-1", "sample-user-3", "sample-user-5"]),
    _count: { tasks: 2 },
  },
];

export const sampleTasks = [
  {
    id: "task-1",
    title: "Verify Railway health endpoint",
    description: "Confirm that the Railway web service is responding.",
    status: "COMPLETED" as TaskStatus,
    priority: "LOW" as Priority,
    dueDate: addDays(1),
    order: 0,
    assignedToId: sampleUser.id,
    createdById: sampleUser.id,
    projectId: "project-1",
    deletedAt: null,
    createdAt: now,
    updatedAt: now,
    assignedTo: sampleTeamMembers[2],
    project: { id: "project-1", title: "Internal Task Manager Rollout" },
    comments: [],
    attachments: [],
  },
  {
    id: "task-2",
    title: "Check manager login flow",
    description: "Make sure managers can sign in and land on the dashboard.",
    status: "IN_PROGRESS" as TaskStatus,
    priority: "MEDIUM" as Priority,
    dueDate: addDays(2),
    order: 1,
    assignedToId: sampleUser.id,
    createdById: sampleUser.id,
    projectId: "project-1",
    deletedAt: null,
    createdAt: now,
    updatedAt: now,
    assignedTo: sampleTeamMembers[1],
    project: { id: "project-1", title: "Internal Task Manager Rollout" },
    comments: [],
    attachments: [],
  },
  {
    id: "task-3",
    title: "Connect production database later",
    description: "Replace sample metadata with Prisma once DATABASE_URL is ready.",
    status: "TODO" as TaskStatus,
    priority: "HIGH" as Priority,
    dueDate: addDays(5),
    order: 2,
    assignedToId: null,
    createdById: sampleUser.id,
    projectId: "project-1",
    deletedAt: null,
    createdAt: now,
    updatedAt: now,
    assignedTo: null,
    project: { id: "project-1", title: "Internal Task Manager Rollout" },
    comments: [],
    attachments: [],
  },
  {
    id: "task-4",
    title: "Review project detail layout",
    description: "Make sure project pages show scope, deadline, status, and related tasks.",
    status: "REVIEW" as TaskStatus,
    priority: "HIGH" as Priority,
    dueDate: addDays(4),
    order: 0,
    assignedToId: sampleUser.id,
    createdById: sampleUser.id,
    projectId: "project-2",
    deletedAt: null,
    createdAt: now,
    updatedAt: now,
    assignedTo: sampleTeamMembers[3],
    project: { id: "project-2", title: "Client Portal Polish" },
    comments: [],
    attachments: [],
  },
  {
    id: "task-5",
    title: "Prepare client deadline summary",
    description: "Create a clean list of upcoming dates and blockers.",
    status: "IN_PROGRESS" as TaskStatus,
    priority: "URGENT" as Priority,
    dueDate: addDays(7),
    order: 1,
    assignedToId: sampleUser.id,
    createdById: sampleUser.id,
    projectId: "project-2",
    deletedAt: null,
    createdAt: now,
    updatedAt: now,
    assignedTo: sampleTeamMembers[4],
    project: { id: "project-2", title: "Client Portal Polish" },
    comments: [],
    attachments: [],
  },
  {
    id: "task-6",
    title: "Finalize role permissions",
    description: "Confirm ADMIN, MANAGER, and MEMBER behavior for demo flows.",
    status: "TODO" as TaskStatus,
    priority: "MEDIUM" as Priority,
    dueDate: addDays(10),
    order: 0,
    assignedToId: sampleUser.id,
    createdById: sampleUser.id,
    projectId: "project-3",
    deletedAt: null,
    createdAt: now,
    updatedAt: now,
    assignedTo: sampleTeamMembers[2],
    project: { id: "project-3", title: "Team Operations Setup" },
    comments: [],
    attachments: [],
  },
  {
    id: "task-7",
    title: "Set weekly reporting template",
    description: "Define what belongs on the dashboard every week.",
    status: "COMPLETED" as TaskStatus,
    priority: "LOW" as Priority,
    dueDate: addDays(12),
    order: 1,
    assignedToId: sampleUser.id,
    createdById: sampleUser.id,
    projectId: "project-3",
    deletedAt: null,
    createdAt: now,
    updatedAt: now,
    assignedTo: sampleTeamMembers[4],
    project: { id: "project-3", title: "Team Operations Setup" },
    comments: [],
    attachments: [],
  },
];

export const sampleComments = [
  {
    id: "comment-1",
    body: "Temporary metadata mode is active.",
    taskId: "task-2",
    userId: sampleUser.id,
    deletedAt: null,
    createdAt: now,
    updatedAt: now,
    user: { id: sampleUser.id, name: sampleUser.name, imageUrl: sampleUser.imageUrl },
  },
];

export function createSampleId(prefix: string) {
  return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

export function toPublicUser(user = sampleUser) {
  return {
    id: user.id,
    name: user.name,
    email: user.email,
    role: user.role,
    imageUrl: user.imageUrl,
  };
}
